Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2018-10, with the labels that each got.

#78 Add `cloudflare_account_member` resource
  README.md
  cloudflare/provider.go
  cloudflare/resource_cloudflare_account_member.go
  website/cloudflare.erb
  website/docs/r/account_member.markdown
Labels: size/L

#121 Add support for importing `account_members`
  cloudflare/resource_cloudflare_account_member.go
  website/docs/r/account_member.markdown
Labels: size/S

#122 Allow setting SSL level to Strict (SSL-Only Origin Pull)
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: size/XS

#125 Fixes markdown where _ALL_ is italicized
  website/docs/r/rate_limit.html.markdown
Labels: size/XS

#124 Correctly set `multi_script` on Enterprise worker imports
  cloudflare/resource_cloudflare_worker_route.go
Labels: size/XS

#128 Ignore `account_member` role ID ordering
  cloudflare/resource_cloudflare_account_member.go
Labels: size/XS

#130 Origin traffic isn't default anymore
  cloudflare/resource_cloudflare_rate_limit.go
Labels: size/XS

#129 Update rate limit validation to allow 1
  cloudflare/resource_cloudflare_rate_limit.go
Labels: size/XS

#127 Adds validation to cloudflare_record to ensure TTL is not set while proxied is true
  cloudflare/resource_cloudflare_record.go
  cloudflare/resource_cloudflare_record_test.go
Labels: size/M

#136 Update `cloudflare_load_balancer_monitor` interval validation
  cloudflare/resource_cloudflare_load_balancer_monitor.go
  cloudflare/resource_cloudflare_load_balancer_monitor_test.go
  website/docs/r/load_balancer_monitor.html.markdown
Labels: size/XS

#135 Fix import of zone lockdowns
  cloudflare/resource_cloudflare_zone_lockdown.go
  cloudflare/resource_cloudflare_zone_lockdown_test.go
Labels: size/XS

#139 Corrects import example for cloudflare_account_member resource
  website/docs/r/account_member.markdown
Labels: size/XS

#137 Update `cloudflare/cloudflare-go` to aa07f8c
  vendor/github.com/cloudflare/cloudflare-go/access_application.go
  vendor/github.com/cloudflare/cloudflare-go/access_policy.go
  vendor/github.com/cloudflare/cloudflare-go/cloudflare.go
  vendor/github.com/cloudflare/cloudflare-go/cpage.go
  vendor/github.com/cloudflare/cloudflare-go/custom_pages.go
  vendor/github.com/cloudflare/cloudflare-go/filter.go
  vendor/github.com/cloudflare/cloudflare-go/firewall_rules.go
  vendor/github.com/cloudflare/cloudflare-go/load_balancing.go
  vendor/vendor.json
Labels: size/XL

#138 Update provider usage/build docs and how to update a dependency
  README.md
Labels: size/M

#143 Improve `Building The Provider` instructions
  README.md
Labels: size/XS

#140 Implement `Update` for `cloudflare_load_balancer_pool`
  cloudflare/resource_cloudflare_load_balancer_pool.go
  cloudflare/resource_cloudflare_load_balancer_pool_test.go
Labels: size/M

#132 Add support for `cloudflare_custom_pages` resource
  cloudflare/provider.go
  cloudflare/resource_cloudflare_custom_pages.go
  cloudflare/validators.go
  website/cloudflare.erb
  website/docs/r/custom_pages.html.markdown
Labels: size/L
