Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2018-09, with the labels that each got.

#112 Update main index docs
  website/docs/index.html.markdown
Labels: size/XS

#111 add support for Workers
  cloudflare/import_cloudflare_worker_route_test.go
  cloudflare/import_cloudflare_worker_script_test.go
  cloudflare/provider.go
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_worker_route.go
  cloudflare/resource_cloudflare_worker_route_test.go
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_worker_script_test.go
  website/cloudflare.erb
  website/docs/r/worker_route.html.markdown
  website/docs/r/worker_script.html.markdown
Labels: size/XXL

#116 Fix page rule polish (off, lossless or lossy)
  cloudflare/resource_cloudflare_page_rule.go
  website/docs/r/page_rule.html.markdown
Labels: size/S

#115 Zone Lockdown Implementation
  cloudflare/provider.go
  cloudflare/resource_cloudflare_zone_lockdown.go
  website/cloudflare.erb
  website/docs/r/zone_lockdown.html.markdown
Labels: size/L
