Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2018-11, with the labels that each got.

#144 Remove validation for `cloudflare_load_balancer_monitor` interval
  cloudflare/resource_cloudflare_load_balancer_monitor.go
Labels: size/XS

#145 Add Access application and policy support
  cloudflare/provider.go
  cloudflare/resource_cloudflare_access_application.go
  cloudflare/resource_cloudflare_access_policy.go
  website/cloudflare.erb
  website/docs/r/access_application.html.markdown
  website/docs/r/access_policy.html.markdown
Labels: size/XL

#147 Add steering policy support to load balancer
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_load_balancer_test.go
  website/docs/r/load_balancer.html.markdown
Labels: size/M

#149 Remove unnecessary trailing comma from examples
  website/docs/r/page_rule.html.markdown
  website/docs/r/zone_settings_override.html.markdown
Labels: size/XS

#151 Compare `cloudflare_record` name without the zone name
  cloudflare/resource_cloudflare_record.go
Labels: size/XS

#152 `s/status/statuses` update for documentation
  website/docs/r/rate_limit.html.markdown
Labels: size/XS

#153 Support load balancer origin weights and session affinity
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_load_balancer_pool.go
  cloudflare/resource_cloudflare_load_balancer_pool_test.go
  cloudflare/resource_cloudflare_load_balancer_test.go
  website/docs/r/load_balancer.html.markdown
  website/docs/r/load_balancer_pool.html.markdown
Labels: size/M

#157 Allow zones to be properly imported
  cloudflare/resource_cloudflare_zone.go
Labels: size/XS

#170 Add `opportunistic_onion` zone setting support
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: size/XS
