Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-06, with the labels that each got.

#321 Add sweeper for `cloudflare_zones`
  GNUmakefile
  cloudflare/cloudflare_sweeper_test.go
  cloudflare/data_source_zones_test.go
Labels: size/M

#369 test/load_balancer_pool: Update IP range for tests
  cloudflare/resource_cloudflare_load_balancer_pool_test.go
Labels: size/XS

#370 Fixing actions block in example
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XS

#381 Add H2 prioritisation and image resizing settings
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#379 Fix browser_cache_ttl page rule action bugs
  cloudflare/import_cloudflare_page_rule_test.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: size/L

#390 Bugfix: browser_cache_ttl is incorrectly sent as a string when unchanged
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: size/XS

#395 Update website/docs/r/logpush_job.html.markdown
  website/docs/r/logpush_job.html.markdown
Labels: documentation, size/XS
