Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-05, with the labels that each got.

#320 Fix page rule and spectrum application import acceptance tests
  cloudflare/import_cloudflare_spectrum_application_test.go
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: size/S

#329 Fixes #328: Support LB traffic steering "Random"
  cloudflare/resource_cloudflare_load_balancer.go
  website/docs/r/load_balancer.html.markdown
Labels: documentation, size/XS

#335 cloudflare_logpush: Remove acceptance test
  cloudflare/resource_cloudflare_logpush_job_test.go
Labels: size/M

#338 page_rules: Swap to completely replacing rules
  cloudflare/resource_cloudflare_page_rule.go
Labels: size/S

#351 Update note on doc
  website/docs/r/access_rule.html.markdown
Labels: documentation, size/XS
