Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-01, with the labels that each got.

#179 Add optional port parameter to load balancer monitors
  cloudflare/resource_cloudflare_load_balancer_monitor.go
  cloudflare/resource_cloudflare_load_balancer_monitor_test.go
  vendor/github.com/cloudflare/cloudflare-go/CODE_OF_CONDUCT.md
  vendor/github.com/cloudflare/cloudflare-go/custom_hostname.go
  vendor/github.com/cloudflare/cloudflare-go/go.sum
  vendor/github.com/cloudflare/cloudflare-go/load_balancing.go
  vendor/github.com/cloudflare/cloudflare-go/zone.go
  vendor/vendor.json
Labels: dependencies, size/L

#182 Improved documentation for priority attribute in page rule resource
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XS

#185 Update page_rule.html.markdown
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XS

#183 Page rule `zone` attribute change to trigger new resource
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: size/S

#172 Add challenge and js_challenge rate-limit modes
  cloudflare/resource_cloudflare_rate_limit.go
  cloudflare/resource_cloudflare_rate_limit_test.go
  website/docs/r/rate_limit.html.markdown
Labels: documentation, size/L

#168 New Data Source: cloudflare_zones
  cloudflare/data_source_zones.go
  cloudflare/data_source_zones_test.go
  cloudflare/provider.go
  website/cloudflare.erb
  website/docs/d/zones.html.md
Labels: documentation, size/XL

#156 [WIP] New Resource: cloudflare_spectrum_app
  cloudflare/import_cloudflare_spectrum_application_test.go
  cloudflare/provider.go
  cloudflare/resource_cloudflare_spectrum_application.go
  cloudflare/resource_cloudflare_spectrum_application_test.go
  website/cloudflare.erb
  website/docs/r/spectrum_application.html.markdown
Labels: documentation, size/XL

#195 Fix type assertion for custom error pages
  cloudflare/resource_cloudflare_custom_pages.go
Labels: size/XS

#197 Add log action for firewall rules
  cloudflare/resource_cloudflare_firewall_rule.go
  website/docs/r/firewall_rule.markdown
Labels: documentation, size/XS

#202 Fix local path in readme.md
  README.md
Labels: size/XS

#200 Fix typo: Requried -> Required
  website/docs/r/spectrum_application.html.markdown
Labels: documentation, size/XS
