Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-04, with the labels that each got.

#275 data_source_zone: Return ID and Name
  cloudflare/data_source_zones.go
  cloudflare/resource_cloudflare_spectrum_application_test.go
  website/docs/d/zones.html.md
Labels: documentation, size/M

#281 Add enabled field to load_balancer (#208)
  cloudflare/resource_cloudflare_load_balancer.go
  website/docs/r/load_balancer.html.markdown
Labels: documentation, size/XS

#284 validators: Allow PTR DNS records
  cloudflare/validators.go
Labels: size/XS

#287 SDK-10 Implement support for LogpushJob
  cloudflare/provider.go
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_logpush_job.go
  cloudflare/resource_cloudflare_logpush_job_test.go
  go.mod
  go.sum
  vendor/github.com/cloudflare/cloudflare-go/logpush.go
  vendor/modules.txt
  website/cloudflare.erb
  website/docs/r/logpush_job.html.markdown
Labels: dependencies, documentation, size/XL

#293 rate_limit: Update action.modes documentation
  website/docs/r/rate_limit.html.markdown
Labels: documentation, size/XS

#291 cloudflare_page_rule: Allow `browser_cache_ttl` of 0
  cloudflare/resource_cloudflare_page_rule.go
Labels: size/XS

#295 Remove tagged release from module
  go.mod
  go.sum
Labels: size/XS

#303 cloudflare_zone: Support partial zones
  cloudflare/resource_cloudflare_zone.go
  cloudflare/resource_cloudflare_zone_test.go
  website/docs/r/zone.html.markdown
Labels: documentation, size/S

#304 cloudflare_argo: Add support for managing Argo
  cloudflare/provider.go
  cloudflare/resource_cloudflare_argo.go
  cloudflare/resource_cloudflare_custom_pages.go
  cloudflare/utils.go
  website/cloudflare.erb
  website/docs/r/argo.html.markdown
Labels: documentation, size/L

#316 page_rule: Add ability to manage minify action
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/M
