Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-08, with the labels that each got.

#418 implement custom ssl resource
  cloudflare/provider.go
  cloudflare/resource_cloudflare_custom_ssl.go
  cloudflare/resource_cloudflare_custom_ssl_test.go
  website/docs/r/custom_ssl.html.markdown
Labels: documentation, size/XL

#442 Update toc for custom_ssl resource
  website/cloudflare.erb
Labels: documentation, size/XS

#445 Added Priority field to cloudflare_zone_lockdown schema
  cloudflare/resource_cloudflare_zone_lockdown.go
  cloudflare/resource_cloudflare_zone_lockdown_test.go
Labels: size/S

#452 Add deprecation notice for `zone`, take 2
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_rate_limit.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_worker_route.go
Labels: breaking-change, size/L

#453 resource/cloudflare_page_rule: Remove `HasChange` for `edge_cache_ttl`
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: bug, regression, size/S

#450 Support use of API tokens in addition to API Keys
  cloudflare/config.go
  cloudflare/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#456 Allow `zone_id` to be `Computed`
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_rate_limit.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_worker_route.go
Labels: size/XS

#437 provider: Use real Terraform version in UA header
  cloudflare/provider.go
Labels: dependencies, size/S

#451 Update to cloudflare-go 0.10.0
  .go-version
  cloudflare/provider.go
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_access_rule.go
  cloudflare/resource_cloudflare_access_rule_test.go
  cloudflare/resource_cloudflare_account_member.go
  cloudflare/resource_cloudflare_worker_route.go
  cloudflare/resource_cloudflare_worker_route_test.go
  cloudflare/resource_cloudflare_worker_script_test.go
  cloudflare/resource_cloudflare_zone.go
  go.mod
  go.sum
  vendor/github.com/cloudflare/cloudflare-go/.travis.yml
  vendor/github.com/cloudflare/cloudflare-go/LICENSE
  vendor/github.com/cloudflare/cloudflare-go/cloudflare.go
  vendor/github.com/cloudflare/cloudflare-go/firewall.go
  vendor/github.com/cloudflare/cloudflare-go/go.mod
  vendor/github.com/cloudflare/cloudflare-go/go.sum
  vendor/github.com/cloudflare/cloudflare-go/options.go
  vendor/github.com/cloudflare/cloudflare-go/organizations.go
  vendor/github.com/cloudflare/cloudflare-go/universal_ssl.go
  vendor/github.com/cloudflare/cloudflare-go/user.go
  vendor/github.com/cloudflare/cloudflare-go/waf.go
  vendor/github.com/cloudflare/cloudflare-go/workers.go
  vendor/github.com/cloudflare/cloudflare-go/workers_kv.go
  vendor/github.com/cloudflare/cloudflare-go/zone.go
  vendor/modules.txt
  website/docs/index.html.markdown
  website/docs/r/access_rule.html.markdown
Labels: breaking-change, dependencies, documentation, size/XL

#462 Mark `zone` to always be Computed
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_rate_limit.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_worker_route.go
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_zone_lockdown.go
Labels: size/XS

#459 Rename "token" to "api_key"
  cloudflare/cloudflare_sweeper_test.go
  cloudflare/config.go
  cloudflare/provider.go
  cloudflare/provider_test.go
  website/docs/index.html.markdown
Labels: breaking-change, documentation, size/S
