Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-11, with the labels that each got.

#525 Add data source for WAF Rules
  cloudflare/data_source_waf_rules.go
  cloudflare/data_source_waf_rules_test.go
  cloudflare/provider.go
  website/cloudflare.erb
  website/docs/d/waf_rules.html.md
Labels: documentation, size/XL

#532 Redo #509
  cloudflare/resource_cloudflare_zone.go
  cloudflare/resource_cloudflare_zone_test.go
  website/docs/r/zone.html.markdown
Labels: documentation, size/XS

#510 Add support for Access Groups
  cloudflare/provider.go
  cloudflare/resource_cloudflare_access_group.go
  cloudflare/resource_cloudflare_access_group_test.go
  website/cloudflare.erb
  website/docs/r/access_group.html.markdown
Labels: dependencies, documentation, size/XL

#541 Add `non_identity` to allowed decision schema
  cloudflare/resource_cloudflare_access_policy.go
Labels: size/XS

#542 cloudflare_zone_settings_override: Add support for 0rtt and http3
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#539 Allow empty string for expected_body in Load Balancer Monitors
  cloudflare/resource_cloudflare_load_balancer_monitor.go
  cloudflare/resource_cloudflare_load_balancer_monitor_test.go
  website/docs/r/load_balancer_monitor.html.markdown
Labels: documentation, size/S

#443 Implement Workers KV Namespaces
  cloudflare/provider.go
  cloudflare/resource_cloudflare_workers_kv_namespace.go
  cloudflare/resource_cloudflare_workers_kv_namespace_test.go
  website/cloudflare.erb
  website/docs/r/workers_kv_namespace.html.markdown
Labels: documentation, size/L
