Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-10, with the labels that each got.

#481 add support for changing traffic type in spectrum apps
  cloudflare/resource_cloudflare_spectrum_application.go
  website/docs/r/spectrum_application.html.markdown
Labels: dependencies, documentation, size/XS

#493 APILIB-901: h2_prioritization setting not able to be set in bulk
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/resource_cloudflare_zone_settings_override_test.go
  cloudflare/utils.go
Labels: size/M

#498 addon zone settings info about default values
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/M

#475 Add support for WAF packages
  cloudflare/provider.go
  cloudflare/resource_cloudflare_waf_package.go
  cloudflare/resource_cloudflare_waf_package_test.go
  website/docs/r/waf_package.html.markdown
Labels: dependencies, documentation, size/XL

#508 Add data source for WAF Groups
  cloudflare/data_source_waf_groups.go
  cloudflare/data_source_waf_groups_test.go
  cloudflare/provider.go
  website/cloudflare.erb
  website/docs/d/waf_groups.html.md
Labels: documentation, size/XL

#506 Add data source for WAF Packages
  cloudflare/data_source_waf_packages.go
  cloudflare/data_source_waf_packages_test.go
  cloudflare/provider.go
  website/cloudflare.erb
  website/docs/d/waf_packages.html.md
Labels: documentation, size/XL

#476 Add support for WAF groups
  cloudflare/provider.go
  cloudflare/resource_cloudflare_waf_group.go
  cloudflare/resource_cloudflare_waf_group_test.go
  website/cloudflare.erb
  website/docs/r/waf_group.html.markdown
Labels: dependencies, documentation, size/XL

#520 small doc improvement for cloudflare_ssl
  website/docs/r/custom_ssl.html.markdown
Labels: documentation, size/XS

#522 sweeper/zones: Sweep all zones
  cloudflare/data_source_zones_test.go
Labels: size/XS

#523 test/custom_ssl: Rotate certificate
  cloudflare/resource_cloudflare_custom_ssl_test.go
Labels: size/XS

#521 Add support for Access Service Tokens
  cloudflare/provider.go
  cloudflare/resource_cloudflare_access_service_tokens.go
  cloudflare/resource_cloudflare_access_service_tokens_test.go
  website/cloudflare.erb
  website/docs/r/access_service_token.html.markdown
Labels: documentation, size/XL

#526 Fix typo, require zone_id instead of zone
  website/docs/r/rate_limit.html.markdown
Labels: documentation, size/XS
