Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-03, with the labels that each got.

#228 Adds missing page rule action documentation
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XS

#232 test/data_source_zones: Fix flakey tests due to domain count
  cloudflare/data_source_zones_test.go
Labels: size/XS

#253 Remove advanced_ddos from Zone Settings
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#271 Bump cloudflare-go to ce422d1b74b3
  cloudflare/resource_cloudflare_rate_limit.go
  go.mod
  go.sum
  vendor/github.com/cloudflare/cloudflare-go/.travis.yml
  vendor/github.com/cloudflare/cloudflare-go/account_members.go
  vendor/github.com/cloudflare/cloudflare-go/duration.go
  vendor/github.com/cloudflare/cloudflare-go/errors.go
  vendor/github.com/cloudflare/cloudflare-go/go.mod
  vendor/github.com/cloudflare/cloudflare-go/go.sum
  vendor/github.com/cloudflare/cloudflare-go/load_balancing.go
  vendor/github.com/cloudflare/cloudflare-go/rate_limiting.go
  vendor/github.com/cloudflare/cloudflare-go/registrar.go
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/modules.txt
Labels: dependencies, size/XL

#270 custom_page: Define `SetID` to save state
  cloudflare/resource_cloudflare_custom_pages.go
Labels: size/XS

#274 Bump cloudflare-go to 4034ff974d99
  go.mod
  go.sum
  vendor/github.com/cloudflare/cloudflare-go/README.md
  vendor/github.com/cloudflare/cloudflare-go/logpush.go
  vendor/github.com/cloudflare/cloudflare-go/zone.go
  vendor/modules.txt
Labels: dependencies, size/L
