Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-07, with the labels that each got.

#361 filters: ignore \n's at the end of expressions
  cloudflare/resource_cloudflare_filter.go
  cloudflare/resource_cloudflare_filter_test.go
Labels: size/XS

#405 Deprecate `tls_1_2_only` for `cloudflare_zone_settings_override`
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#409 test/spectrum_application: Add test sweeper
  cloudflare/resource_cloudflare_spectrum_application_test.go
Labels: size/S

#407 Fix: examples of cloudflare_zone_lockdown in documentation
  website/docs/d/zones.html.md
  website/docs/r/zone_lockdown.html.markdown
Labels: documentation, size/XS

#413 Update test names to trigger acceptance tests
  cloudflare/resource_cloudflare_filter_test.go
  cloudflare/resource_cloudflare_firewall_rule_test.go
  cloudflare/resource_cloudflare_zone_lockdown_test.go
  cloudflare/resource_cloudflare_zone_test.go
Labels: size/XS

#412 resource/cloudflare_zone: Add unicode support
  cloudflare/resource_cloudflare_zone.go
  cloudflare/resource_cloudflare_zone_test.go
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: dependencies, size/M

#415 resource/cloudflare_zone_override: Remove `sha1_support`
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#416 resource/cloudflare_zone: Update test domain
  cloudflare/resource_cloudflare_zone_test.go
Labels: size/S

#420 example of include = generates an error
  website/docs/r/access_policy.html.markdown
Labels: documentation, size/XS

#423 Move zone tests under `cfapi.net`
  cloudflare/data_source_zones_test.go
Labels: size/XS

#421 Deprecation for `zone` in favour of explicit `zone_id`
  cloudflare/resource_cloudflare_access_rule.go
  cloudflare/resource_cloudflare_filter.go
  cloudflare/resource_cloudflare_firewall_rule.go
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_rate_limit.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_worker_route.go
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_zone_lockdown.go
Labels: size/M

#430 Closes #429 SSL: adding support for origin_pull setting
  cloudflare/resource_cloudflare_page_rule.go
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XS

#428 Add a 'tcp' type monitor to cloudflare_load_balancer_monitor
  cloudflare/resource_cloudflare_load_balancer_monitor.go
  cloudflare/resource_cloudflare_load_balancer_monitor_test.go
  website/docs/r/load_balancer_monitor.html.markdown
Labels: blocked, documentation, size/XL
