Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-02, with the labels that each got.

#207 Fix typo.
  website/docs/r/firewall_rule.markdown
Labels: documentation, size/XS

#212 provider: Enable request/response logging
  cloudflare/provider.go
Labels: enhancement, size/XS

#213 resource/cloudflare_load_balancer_monitor: Fix incorrect type cast for port
  cloudflare/resource_cloudflare_load_balancer_monitor.go
  cloudflare/resource_cloudflare_record_test.go
Labels: bug, crash, size/XS

#204 Pass `RateLimitCorrelate` to `flattenRateLimitCorrelate`
  cloudflare/resource_cloudflare_rate_limit.go
Labels: size/XS

#205 Add `allow_insecure` and `follow_redirects` to load balancer monitor
  cloudflare/resource_cloudflare_load_balancer_monitor.go
  website/docs/r/load_balancer_monitor.html.markdown
Labels: documentation, size/S

#214 tests: Fix cloudflare_load_balancer acceptance tests
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_load_balancer_test.go
  website/docs/r/load_balancer.html.markdown
Labels: bug, documentation, size/XS

#215 tests/cloudflare_access_rule: Fix acceptance test
  cloudflare/resource_cloudflare_access_rule_test.go
Labels: size/XS

#216 tests/cloudflare_record_test: Fix acceptance test values
  cloudflare/resource_cloudflare_record_test.go
Labels: size/XS

#217 test/cloudflare_record: Fix acceptance LOC tests
  CHANGELOG.md
  cloudflare/resource_cloudflare_record.go
  cloudflare/resource_cloudflare_record_test.go
Labels: size/S

#221 Add missing quotation mark
  website/docs/r/waf_rule.html.markdown
Labels: documentation, size/XS

#218 test/cloudflare_page_rule: Remove not working unitary field updates
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: size/XS

#222 Include example of a record that uses the data argument
  website/docs/r/record.html.markdown
Labels: documentation, size/XS
