Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-09, with the labels that each got.

#463 Update example resources to v0.12 syntax, and fix depends_on for worker_route
  website/docs/r/access_policy.html.markdown
  website/docs/r/access_rule.html.markdown
  website/docs/r/firewall_rule.markdown
  website/docs/r/load_balancer.html.markdown
  website/docs/r/page_rule.html.markdown
  website/docs/r/rate_limit.html.markdown
  website/docs/r/record.html.markdown
  website/docs/r/worker_route.html.markdown
  website/docs/r/worker_script.html.markdown
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/S

#467 Update cloudflare page rule attribute
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XS

#468 Remove use_account_from_zone for v2.0 refactor
  cloudflare/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#469 Missing = sign in the configuration block
  website/docs/r/access_rule.html.markdown
Labels: documentation, size/XS

#472 SDK-80: Zone to zone_id refactoring
  cloudflare/data_source_ip_ranges_test.go
  cloudflare/import_cloudflare_load_balancer_test.go
  cloudflare/import_cloudflare_page_rule_test.go
  cloudflare/import_cloudflare_rate_limit_test.go
  cloudflare/import_cloudflare_waf_rule_test.go
  cloudflare/import_cloudflare_worker_route_test.go
  cloudflare/import_cloudflare_worker_script_test.go
  cloudflare/import_resource_cloudflare_record_test.go
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_access_rule.go
  cloudflare/resource_cloudflare_filter.go
  cloudflare/resource_cloudflare_filter_test.go
  cloudflare/resource_cloudflare_firewall_rule.go
  cloudflare/resource_cloudflare_firewall_rule_test.go
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_load_balancer_test.go
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
  cloudflare/resource_cloudflare_rate_limit.go
  cloudflare/resource_cloudflare_rate_limit_test.go
  cloudflare/resource_cloudflare_record.go
  cloudflare/resource_cloudflare_record_test.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_waf_rule_test.go
  cloudflare/resource_cloudflare_worker_route.go
  cloudflare/resource_cloudflare_worker_route_test.go
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_worker_script_test.go
  cloudflare/resource_cloudflare_zone_lockdown.go
  cloudflare/resource_cloudflare_zone_lockdown_test.go
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/resource_cloudflare_zone_settings_override_test.go
  go.mod
  go.sum
  website/docs/r/access_rule.html.markdown
  website/docs/r/filter.markdown
  website/docs/r/firewall_rule.markdown
  website/docs/r/load_balancer.html.markdown
  website/docs/r/page_rule.html.markdown
  website/docs/r/rate_limit.html.markdown
  website/docs/r/record.html.markdown
  website/docs/r/waf_rule.html.markdown
  website/docs/r/worker_route.html.markdown
  website/docs/r/worker_script.html.markdown
  website/docs/r/zone_lockdown.html.markdown
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XXL

#477 Handle the errors when fetching data for the Argo resource
  cloudflare/resource_cloudflare_argo.go
Labels: size/XS

#478 SDK-81: Refactor Workers resources to remove single-script code.
  cloudflare/import_cloudflare_worker_route_test.go
  cloudflare/import_cloudflare_worker_script_test.go
  cloudflare/resource_cloudflare_worker_route.go
  cloudflare/resource_cloudflare_worker_route_test.go
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_worker_script_test.go
  website/docs/r/worker_route.html.markdown
  website/docs/r/worker_script.html.markdown
Labels: breaking-change, documentation, size/XL

#480 Version 2 Upgrade Guide
  website/cloudflare.erb
  website/docs/guides/version-2-upgrade.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/L
