Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2019-12, with the labels that each got.

#544 Add support for Worker KV Namespace Bindings
  cloudflare/import_cloudflare_worker_script_test.go
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_worker_script_test.go
  website/docs/r/worker_script.html.markdown
Labels: documentation, size/L

#549 Spectrum origin_port is optional
  cloudflare/resource_cloudflare_spectrum_application.go
  website/docs/r/spectrum_application.html.markdown
Labels: documentation, size/XS

#550 Support allowed modes for WAF Rules
  cloudflare/data_source_waf_rules.go
  cloudflare/import_cloudflare_waf_rule_test.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_waf_rule_test.go
  website/docs/d/waf_rules.html.md
Labels: documentation, size/M

#556 Fix typo in import command's resource
  website/docs/r/firewall_rule.markdown
Labels: documentation, size/XS

#557 zone_settings_overrid: Remap 0rtt attribute name to zero_rtt
  CHANGELOG.md
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/resource_cloudflare_zone_settings_override_test.go
  website/docs/r/zone_settings_override.html.markdown
Labels: bug, documentation, size/XS

#560 Add ip6 as valid type for access rules
  cloudflare/resource_cloudflare_access_rule.go
  website/docs/r/access_rule.html.markdown
Labels: documentation, size/XS

#562 update Spectrum application resource to use string enum for proxy_pro…
  cloudflare/resource_cloudflare_spectrum_application.go
  website/docs/r/spectrum_application.html.markdown
Labels: documentation, size/XS

#547 Implement Origin CA certificate resource
  cloudflare/config.go
  cloudflare/provider.go
  cloudflare/resource_cloudflare_origin_ca_certificate.go
  cloudflare/resource_cloudflare_origin_ca_certificate_test.go
  website/cloudflare.erb
  website/docs/index.html.markdown
  website/docs/r/origin_ca_certificate.html.markdown
Labels: dependencies, documentation, size/XL

#552 Improvements to the `cloudflare_waf_rule` resource
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/resource_cloudflare_waf_rule_test.go
  website/docs/r/waf_rule.html.markdown
Labels: documentation, size/M

#566 Use zone_id if available and fallback on domain for record state migration
  cloudflare/resource_cloudflare_record_migrate.go
  cloudflare/resource_cloudflare_record_migrate_test.go
Labels: size/M
