Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-07, with the labels that each got.

#732 test/spectrum_application: Remove zone listing calls
  cloudflare/import_cloudflare_spectrum_application_test.go
  cloudflare/resource_cloudflare_spectrum_application_test.go
Labels: size/M

#725 resource/access_application: Add CORS support
  cloudflare/resource_cloudflare_access_application.go
  cloudflare/resource_cloudflare_access_application_test.go
  website/docs/r/access_application.html.markdown
Labels: documentation, size/L

#730 Access: add support for auto_redirect_to_identity
  cloudflare/resource_cloudflare_access_application.go
  cloudflare/resource_cloudflare_access_application_test.go
  website/docs/r/access_application.html.markdown
Labels: documentation, size/M

#734 access: add support for allowed_idps
  cloudflare/resource_cloudflare_access_application.go
  cloudflare/resource_cloudflare_access_application_test.go
  website/docs/r/access_application.html.markdown
Labels: documentation, size/M
