Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-03, with the labels that each got.

#564 Handle errors properly in Logpush resource
  cloudflare/resource_cloudflare_logpush_job.go
Labels: size/XS

#610 adds validation to only allow valid DNS record types
  cloudflare/resource_cloudflare_record.go
Labels: size/XS

#597 Add support for Access Identity Provider
  cloudflare/provider.go
  cloudflare/resource_cloudflare_access_identity_provider.go
  cloudflare/resource_cloudflare_access_identity_provider_test.go
  website/cloudflare.erb
  website/docs/r/access_identity_provider.html.markdown
Labels: documentation, size/XL, wip

#617 datasource/ip_ranges: Update usage documentation
  website/docs/d/ip_ranges.html.md
Labels: documentation, size/XS

#618 resource/logpush_job: Add support for import
  cloudflare/resource_cloudflare_logpush_job.go
Labels: size/XS

#612 Support service_token for cloudflare_access_policy
  cloudflare/resource_cloudflare_access_policy.go
  cloudflare/resource_cloudflare_access_policy_test.go
  website/docs/r/access_policy.html.markdown
Labels: documentation, pending/contributor-response, size/L

#623 resources: WAF: handles properly when the target has been deleted on Cloudflare's side
  cloudflare/resource_cloudflare_waf_group.go
  cloudflare/resource_cloudflare_waf_package.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/utils.go
Labels: size/M

#629 Use the correct method for fetching all provider
  cloudflare/resource_cloudflare_access_identity_provider_test.go
Labels: size/XS

#626 Add support for Access Groups in policies
  cloudflare/resource_cloudflare_access_policy.go
  cloudflare/resource_cloudflare_access_policy_test.go
  website/docs/r/access_policy.html.markdown
Labels: documentation, pending/contributor-response, size/M

#630 Fix firewall rule products support which was missing handling
  cloudflare/resource_cloudflare_firewall_rule.go
  cloudflare/resource_cloudflare_firewall_rule_test.go
  cloudflare/utils.go
Labels: size/M

#631 SDK-88: Add edge_ips, argo_smart_routing support for Spectrum
  cloudflare/resource_cloudflare_spectrum_application.go
  website/docs/r/spectrum_application.html.markdown
Labels: documentation, size/M

#633 Add support for external Access Groups
  cloudflare/resource_cloudflare_access_group.go
  cloudflare/resource_cloudflare_access_policy.go
  cloudflare/resource_cloudflare_access_policy_test.go
  website/docs/r/access_group.html.markdown
  website/docs/r/access_policy.html.markdown
Labels: documentation, size/XL

#636 Spelling fix
  website/docs/r/load_balancer_pool.html.markdown
Labels: documentation, size/XS

#637 Spelling fix
  website/docs/r/load_balancer.html.markdown
Labels: documentation, size/XS

#639 Add 'open' option for image_resizing setting
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS
