Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-05, with the labels that each got.

#671 Adds new resource cloudflare_byo_ip_prefix
  cloudflare/provider.go
  cloudflare/provider_test.go
  cloudflare/resource_cloudflare_byo_ip_prefix.go
  cloudflare/resource_cloudflare_byo_ip_prefix_test.go
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/utils.go
  website/docs/r/byo_ip_prefix.html.markdown
Labels: documentation, size/L

#677 Update import example command to reflect reality
  website/docs/r/record.html.markdown
Labels: documentation, size/XS

#678 resource/logpull_retention: Adds new resource
  cloudflare/provider.go
  cloudflare/resource_cloudflare_logpull_retention.go
  cloudflare/resource_cloudflare_logpull_retention_test.go
  website/cloudflare.erb
  website/docs/r/logpull_retention.html.markdown
Labels: documentation, size/L

#679 Fix Copy/Paste error in sidebar_current for cloudflare_byo_ip_prefix
  website/docs/r/byo_ip_prefix.html.markdown
Labels: documentation, size/XS

#680 Adds new resource cloudflare_healthcheck
  cloudflare/provider.go
  cloudflare/resource_cloudflare_healthcheck.go
  cloudflare/resource_cloudflare_healthcheck_test.go
  website/docs/r/healthcheck.html.markdown
Labels: documentation, size/XL

#687 Further describe notification_email of cloudflare_load_balancer_pool
  website/docs/r/load_balancer_pool.html.markdown
Labels: documentation, size/XS

#685 SDK-91 Terraform support for 'cache_key_fields' page rule field
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
  cloudflare/utils.go
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/XL

#689 Update docs to denote plan-dependent arguments
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#692 Adds/Fixes links in cloudflare.erb
  website/cloudflare.erb
Labels: documentation, size/XS

#691 new resource: WAF overrides
  cloudflare/provider.go
  cloudflare/resource_cloudflare_waf_override.go
  cloudflare/resource_cloudflare_waf_override_test.go
  website/cloudflare.erb
  website/docs/r/waf_override.html.markdown
Labels: documentation, size/XL
