Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-06, with the labels that each got.

#703 resource/cloudflare_argo: Allow settings to be individually customised
  cloudflare/resource_cloudflare_argo.go
  cloudflare/resource_cloudflare_argo_test.go
  website/docs/r/argo.html.markdown
Labels: documentation, size/M

#712 Update asserted TestAccCloudflareRecord_LOC string
  cloudflare/resource_cloudflare_record_test.go
Labels: size/XS

#713 Update TestAccCloudflareRecord_Basic metadata count
  cloudflare/resource_cloudflare_record_test.go
Labels: size/XS

#706 SDK-95: cache_ttl_by_status support for Page Rules
  cloudflare/resource_cloudflare_page_rule.go
  cloudflare/resource_cloudflare_page_rule_test.go
  website/docs/r/page_rule.html.markdown
Labels: documentation, size/L

#710 Add support for worker text bindings
  cloudflare/resource_cloudflare_worker_script.go
  cloudflare/resource_cloudflare_worker_script_test.go
  website/docs/r/worker_script.html.markdown
Labels: documentation, size/L

#716 Restrict zone sweeper to account ID
  cloudflare/data_source_zones_test.go
Labels: size/XS

#714 adds support for CustomSSLOptions GeoRestrictions to be nil
  cloudflare/resource_cloudflare_custom_ssl.go
  cloudflare/resource_cloudflare_custom_ssl_test.go
Labels: size/S

#708 datasource/zones: Perform filtering on server side
  cloudflare/data_source_zones.go
  cloudflare/data_source_zones_test.go
  website/docs/d/zones.html.md
Labels: documentation, size/L
