Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-04, with the labels that each got.

#646 access_group: Consolidate access conditions schema
  cloudflare/resource_cloudflare_access_group.go
  cloudflare/resource_cloudflare_access_policy.go
Labels: size/L

#651 Remove workaround for Access not supporting API tokens
  cloudflare/resource_cloudflare_access_policy_test.go
Labels: size/S

#654 resource/zone_settings_override: Remove `edge_cache_ttl`
  cloudflare/resource_cloudflare_zone_settings_override.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS

#649 resource/logpush_job: Add support for "dataset" parameter
  cloudflare/resource_cloudflare_logpush_job.go
  website/docs/r/logpush_job.html.markdown
Labels: documentation, size/XS

#647 Travis CI migration GitHub actions
  .github/workflows/unit-tests.yml
  .github/workflows/website.yml
  .travis.yml
  GNUmakefile
  cloudflare/resource_cloudflare_logpush_job.go
Labels: size/M, wip

#656 Fix cloudflare_access_group.service_token example to mention a list of ids
  website/docs/r/access_group.html.markdown
Labels: documentation, size/XS

#660 Add missing 'firewall_events' dataset to cloudflare_logpush_job.
  cloudflare/resource_cloudflare_logpush_job.go
  website/docs/r/logpush_job.html.markdown
Labels: documentation, size/XS

#661 provider: Add validation for tokens and keys
  cloudflare/provider.go
Labels: size/XS

#658 Adds cloudflare_universal_ssl resource controlling USSL status
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/resource_cloudflare_zone_settings_override_test.go
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/M

#666 logpush_ownership_challenge: Add new resource
  cloudflare/provider.go
  cloudflare/resource_cloudflare_logpush_ownership_challenge.go
  cloudflare/resource_cloudflare_logpush_ownership_challenge_test.go
  website/cloudflare.erb
  website/docs/r/logpush_job.html.markdown
  website/docs/r/logpush_ownership_challenge.html.markdown
Labels: documentation, size/L

#663 checks if universal_ssl is set in resource configuration to avoid permission issues with strictly scoped API tokens
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/resource_cloudflare_zone_settings_override_test.go
Labels: regression, size/S

#669 resource/cloudflare_worker_route: Add note about needing `account_id`
  website/docs/r/worker_route.html.markdown
Labels: documentation, size/XS

#670 Add note mentioning use of `account_id`
  website/docs/r/worker_script.html.markdown
Labels: documentation, size/XS

#668 resource/cloudflare_zone: No need to translate the ID to Name back to ID
  cloudflare/resource_cloudflare_zone.go
Labels: size/XS
