Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-02, with the labels that each got.

#599 Apply Single Zone Settings on Delete
  cloudflare/resource_cloudflare_zone_settings_override.go
  cloudflare/resource_cloudflare_zone_settings_override_test.go
Labels: size/M

#595 Add worker kv
  cloudflare/provider.go
  cloudflare/resource_cloudflare_worker_kv.go
  cloudflare/resource_cloudflare_worker_kv_test.go
  website/cloudflare.erb
  website/docs/r/workers_kv.html.markdown
Labels: documentation, size/L

#606 document `cache_level` settings with their meaning
  website/docs/r/zone_settings_override.html.markdown
Labels: documentation, size/XS
