Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-08, with the labels that each got.

#745 Support Spectrum applications with port ranges
  cloudflare/resource_cloudflare_spectrum_application.go
  cloudflare/resource_cloudflare_spectrum_application_test.go
  website/docs/r/spectrum_application.html.markdown
Labels: documentation, size/M

#749 Add support for configuring authenticated origin pulls
  cloudflare/provider.go
  cloudflare/resource_cloudflare_authenticated_origin_pulls.go
  cloudflare/resource_cloudflare_authenticated_origin_pulls_certificate.go
  cloudflare/resource_cloudflare_authenticated_origin_pulls_certificate_test.go
  cloudflare/resource_cloudflare_authenticated_origin_pulls_test.go
  website/docs/r/authenticated_origin_pulls.html.markdown
  website/docs/r/authenticated_origin_pulls_certificate.html.markdown
Labels: pending/contributor-response

#774 Adding undocumented CF access session_duration values 0s and 15m
  cloudflare/resource_cloudflare_access_application.go
  website/docs/r/access_application.html.markdown
Labels: blocked, pending/cloudflare-response

#724 Update access resources to use account_id over zone_id
  cloudflare/resource_cloudflare_access_application.go
  cloudflare/resource_cloudflare_access_application_test.go
  cloudflare/resource_cloudflare_access_policy.go
  cloudflare/resource_cloudflare_access_policy_test.go
  cloudflare/utils.go
Labels: size/XL
