Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2020-01, with the labels that each got.

#573 cloudflare_load_balancer: add ip_cookie as a valid session_affinity option
  cloudflare/resource_cloudflare_load_balancer.go
  cloudflare/resource_cloudflare_load_balancer_test.go
  website/docs/r/load_balancer.html.markdown
Labels: documentation, size/S

#568 Add firewall rule bypass and products supports
  cloudflare/resource_cloudflare_firewall_rule.go
  website/docs/r/firewall_rule.markdown
Labels: blocked, documentation, size/XS, upstream

#586 update certificate for tests
  cloudflare/resource_cloudflare_custom_ssl_test.go
Labels: size/XS

#587 Add attributes reference for cloudflare_access_application
  website/docs/r/access_application.html.markdown
Labels: documentation, size/XS

#590 datasource/waf_rules: Update test to check presence instead of value
  cloudflare/data_source_waf_rules_test.go
Labels: size/XS

#591 test/firewall_rule: Add sweeper
  cloudflare/resource_cloudflare_filter_test.go
  cloudflare/resource_cloudflare_firewall_rule_test.go
Labels: size/M
