Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-12, with the labels that each got.

#2078 fix pages variable types
  internal/provider/resource_cloudflare_pages_project.go
Labels: workflow/skip-changelog-entry

#1228 Add data source load balancer pools
  .changelog/1228.txt
  docs/data-sources/load_balancer_pools.md
  examples/data-sources/cloudflare_load_balancer_pools/data-source.tf
  internal/provider/data_source_load_balancer_pools.go
  internal/provider/data_source_load_balancer_pools_test.go
  internal/provider/provider.go
  internal/provider/schema_cloudflare_load_balancer_pool.go
Labels: lifecycle/stale

#1878 add cloudflare_url_normalization_settings resource
  .changelog/1878.txt
  docs/resources/url_normalization_settings.md
  examples/resources/cloudflare_url_normalization_settings/resource.tf
  internal/provider/provider.go
  internal/provider/resource_cloudflare_url_normalization_settings.go
  internal/provider/resource_cloudflare_url_normalization_settings_test.go
  internal/provider/schema_cloudflare_url_normalization_settings.go
Labels: workflow/pending-cloudflare-response

#2103 Tidy up makefile
  GNUmakefile
Labels: workflow/skip-changelog-entry

#2106 tests: skip known broken/unreliable tests pending investigation
  internal/provider/import_resource_cloudflare_zone_dnssec_test.go
  internal/provider/resource_cloudflare_account_member_test.go
  internal/provider/resource_cloudflare_account_test.go
  internal/provider/resource_cloudflare_authenticated_origin_pulls_certificate_test.go
  internal/provider/resource_cloudflare_pages_domain_test.go
  internal/provider/resource_cloudflare_pages_project_test.go
Labels: workflow/skip-changelog-entry

#2111 resource/cloudflare_zone_dnssec: migrate to autogen docs
  docs/resources/zone_dnssec.md
  examples/resources/cloudflare_zone_dnssec/import.sh
  examples/resources/cloudflare_zone_dnssec/resource.tf
  internal/provider/resource_cloudflare_zone_dnssec.go
  internal/provider/schema_cloudflare_zone_dnssec.go
  templates/resources/zone_dnssec.md
Labels: workflow/skip-changelog-entry

#2112 resource/cloudflare_record: move to autogen docs
  docs/resources/record.md
  examples/resources/cloudflare_record/import.sh
  examples/resources/cloudflare_record/resource.tf
  internal/provider/resource_cloudflare_record.go
  internal/provider/schema_cloudflare_record.go
  templates/resources/record.md
Labels: workflow/skip-changelog-entry
