Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-08, with the labels that each got.

#1839 fix: doc: loadbalancing region URL
  docs/resources/load_balancer_pool.md
  templates/resources/load_balancer_pool.md
Labels: workflow/skip-changelog-entry

#1825 Add r2_bucket_binding to cloudflare_worker_script
  .changelog/1825.txt
  docs/resources/worker_script.md
  internal/provider/resource_cloudflare_worker_script.go
  internal/provider/resource_cloudflare_worker_script_test.go
  internal/provider/schema_cloudflare_worker_script.go
Labels: workflow/pending-upstream-library

#1862 docs: hint at more schema conditions for `ExactlyOneOf`, `AtLeastOneOf` and `RequiredWith`
  docs/data-sources/access_identity_provider.md
  docs/data-sources/zone.md
  docs/index.md
  docs/resources/access_policy.md
  docs/resources/access_rule.md
  docs/resources/logpush_job.md
  docs/resources/notification_policy.md
  docs/resources/ruleset.md
  internal/provider/provider.go
  templates/resources/worker_script.md
Labels: workflow/skip-changelog-entry

#1864 Fix typo in cloudflare_zone for jump_start description
  docs/resources/zone.md
  internal/provider/schema_cloudflare_zone.go
Labels: kind/documentation, workflow/skip-changelog-entry

#1875 bump everything CI to Go 1.18
  .github/workflows/acceptance-tests.yml
  .github/workflows/changelog-check.yml
  .github/workflows/lint.yml
  .github/workflows/maintainer-only-files.yml
  .github/workflows/release.yml
  .github/workflows/terraform-log-check.yml
  .github/workflows/unit-tests.yml
Labels: workflow/skip-changelog-entry
