Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-01, with the labels that each got.

#1340 WDAPI-645 add a device posture integration
  cloudflare/provider.go
  cloudflare/resource_cloudflare_device_posture_integration.go
  cloudflare/resource_cloudflare_device_posture_integration_test.go
  cloudflare/resource_cloudflare_device_posture_rule.go
  cloudflare/schema_cloudflare_device_posture_integration.go
  cloudflare/schema_cloudflare_device_posture_rule.go
  website/docs/r/device_posture_integration.html.markdown
Labels: kind/enhancement, kind/new-resource

#1375 moar lint!
  .github/workflows/lint.yml
  .golintci.yml
Labels: workflow/skip-changelog-entry

#1356 Adding support for fallback domains
  .changelog/1356.txt
  cloudflare/provider.go
  cloudflare/resource_cloudflare_fallback_domain.go
  cloudflare/resource_cloudflare_fallback_domain_test.go
  cloudflare/schema_cloudflare_fallback_domain.go
  website/cloudflare.erb
  website/docs/r/fallback_domain.html.markdown
Labels: kind/enhancement, kind/new-resource

#1396 resource/cloudflare_page_rule: add test sweepers
  cloudflare/resource_cloudflare_page_rule_test.go
Labels: workflow/skip-changelog-entry

#1395 resource/cloudflare_device_posture_integration: don't output debug in CI
  cloudflare/resource_cloudflare_device_posture_integration.go
Labels: workflow/skip-changelog-entry

#1411 bump to cloudflare-go@v0.31.0
  go.mod
  go.sum
Labels: workflow/skip-changelog-entry

#1399 cloudflare_fallback_domain support for default entries
  .changelog/1399.txt
  cloudflare/resource_cloudflare_fallback_domain.go
  cloudflare/resource_cloudflare_fallback_domain_test.go
  website/docs/r/fallback_domain.html.markdown
Labels: workflow/pending-upstream-library

#1386 GATE-2293 added teams logging, fips and url browser isolation settings
  cloudflare/resource_cloudflare_teams_accounts.go
  cloudflare/resource_cloudflare_teams_accounts_test.go
  cloudflare/schema_cloudflare_teams_accounts.go
  website/docs/r/teams_account.html.markdown
Labels: workflow/pending-op-response
