Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-11, with the labels that each got.

#1960 ACCT-4178: Add raw permissions struct to provider
  .changelog/1960.txt
  docs/data-sources/api_token_permission_groups.md
  examples/data-sources/cloudflare_api_token_permission_groups/data-source.tf
  internal/provider/data_source_api_token_permission_groups.go
  internal/provider/data_source_api_token_permission_groups_test.go
  templates/data-sources/api_token_permission_groups.md
Labels: workflow/pending-contributor-response

#2025 Support worker_trace_events dataset in logspush jobs
  .changelog/2025.txt
  docs/resources/logpush_job.md
  internal/provider/schema_cloudflare_logpush_job.go
Labels: workflow/pending-public-documentation

#2036 resource/cloudflare_account: always send the settings payload
  internal/provider/resource_cloudflare_account.go
  internal/provider/resource_cloudflare_account_test.go
Labels: workflow/skip-changelog-entry

#2050 resource/cloudflare_logpush_job: swap string check for 404 for NotFoundError
  internal/provider/resource_cloudflare_logpush_job.go
Labels: workflow/skip-changelog-entry

#2053 docs: clean up whitespace in md templates
  docs/data-sources/accounts.md
  docs/data-sources/api_token_permission_groups.md
  docs/data-sources/record.md
  docs/resources/access_organization.md
  docs/resources/access_rule.md
  docs/resources/access_service_token.md
  docs/resources/account.md
  docs/resources/account_member.md
  docs/resources/argo.md
  docs/resources/byo_ip_prefix.md
  docs/resources/custom_hostname.md
  docs/resources/device_posture_rule.md
  docs/resources/device_settings_policy.md
  docs/resources/dlp_profile.md
  docs/resources/fallback_domain.md
  docs/resources/filter.md
  docs/resources/healthcheck.md
  docs/resources/ipsec_tunnel.md
  docs/resources/list.md
  docs/resources/logpush_job.md
  docs/resources/notification_policy.md
  docs/resources/pages_domain.md
  docs/resources/pages_project.md
  docs/resources/split_tunnel.md
  docs/resources/tunnel_route.md
  docs/resources/tunnel_virtual_network.md
  docs/resources/waiting_room.md
  docs/resources/waiting_room_event.md
  docs/resources/waiting_room_rules.md
  templates/data-sources.md.tmpl
  templates/resources.md.tmpl
Labels: workflow/skip-changelog-entry
