Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-04, with the labels that each got.

#1548 formatting and simplification of test params
  cloudflare/resource_cloudflare_api_token_test.go
Labels: workflow/skip-changelog-entry

#1555 release cleanup
  .changelog/1412.txt
  .changelog/1554.txt
  CHANGELOG.md
  website/docs/r/ruleset.html.markdown
Labels: workflow/skip-changelog-entry

#1538 Add logging configuration for rulesets rules
  .changelog/1538.txt
  cloudflare/resource_cloudflare_ruleset.go
  cloudflare/resource_cloudflare_ruleset_test.go
  cloudflare/schema_cloudflare_ruleset.go
  website/docs/r/ruleset.html.markdown
Labels: workflow/pending-upstream-library

#1478 Add support managed_challenge for custom_pages
  .changelog/1478.txt
  cloudflare/schema_cloudflare_custom_pages.go
  website/docs/r/custom_pages.html.markdown
Labels: workflow/pending-public-documentation

#1567 Add ability to wait for cert packs to be active
  .changelog/1567.txt
  cloudflare/resource_cloudflare_certificate_pack.go
  cloudflare/resource_cloudflare_certificate_pack_test.go
  cloudflare/schema_cloudflare_certificate_pack.go
  website/docs/r/certificate_pack.html.markdown
Labels: workflow/pending-op-response

#1550 Adding IP type support for cloudflare teams list
  .changelog/1550.txt
  cloudflare/schema_cloudflare_teams_list.go
  tools/tools.go
  website/docs/r/teams_list.html.markdown
Labels: workflow/pending-public-documentation
