Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-03, with the labels that each got.

#1467 WDAPI-804 add device policy client certificate zone
  .changelog/1467.txt
  cloudflare/provider.go
  cloudflare/resource_cloudflare_device_policy.go
  cloudflare/resource_cloudflare_device_policy_test.go
  cloudflare/schema_cloudflare_device_policy_certificates.go
  website/cloudflare.erb
  website/docs/r/device_policy_certificates.html.markdown
Labels: workflow/pending-upstream-library

#1504 [resource/device_posture_integration] Remove extra id parameters
  .changelog/1504.txt
  cloudflare/schema_cloudflare_device_posture_integration.go
Labels: workflow/pending-op-response

#1531 incorporate error handling fixes from cloudflare/cloudflare-go#839
  cloudflare/resource_cloudflare_access_keys_configuration.go
  cloudflare/resource_cloudflare_custom_hostname_fallback_origin.go
  cloudflare/resource_cloudflare_waf_group.go
  cloudflare/resource_cloudflare_waf_package.go
  cloudflare/resource_cloudflare_waf_rule.go
  cloudflare/utils.go
Labels: workflow/pending-upstream-library, workflow/skip-changelog-entry
