Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-02, with the labels that each got.

#1418 fix cloudflare_teams_account docs
  website/docs/r/teams_account.html.markdown
Labels: kind/documentation, service/access, workflow/skip-changelog-entry

#1431 feat(rate_limit): add support for managed_challenge
  .changelog/1431.txt
  cloudflare/schema_cloudflare_rate_limit.go
  website/docs/r/rate_limit.html.markdown
Labels: workflow/pending-public-documentation

#1447 adds automation for detecting unwanted changes
  .github/workflows/maintainer-only-files.yml
  tools/cmd/maintainer-only-file-check/main.go
Labels: workflow/skip-changelog-entry

#1423 Adds support for Magic Transit GRE tunnels
  .changelog/1423.txt
  cloudflare/provider.go
  cloudflare/resource_cloudflare_gre_tunnel.go
  cloudflare/resource_cloudflare_gre_tunnel_test.go
  cloudflare/schema_cloudflare_gre_tunnel.go
  website/cloudflare.erb
  website/docs/r/gre_tunnel.html.markdown
Labels: kind/enhancement, service/magic_transit

#1461 restrict tf-log-check to bug issue types
  tools/cmd/tf-log-check/main.go
Labels: workflow/skip-changelog-entry

#1480 tools: clean up maintainer-only-file-check
  tools/cmd/maintainer-only-file-check/main.go
Labels: workflow/skip-changelog-entry

#1477 resource/cloudflare_ruleset: rename `mitigation_expression` to `counting_expression`
  .changelog/1477.txt
  cloudflare/resource_cloudflare_ruleset.go
  cloudflare/resource_cloudflare_ruleset_migrate.go
  cloudflare/resource_cloudflare_ruleset_migrate_test.go
  cloudflare/schema_cloudflare_ruleset.go
Labels: workflow/pending-upstream-library

#1469 Teams rule setting disable dnssec validation option
  .changelog/1469.txt
  cloudflare/resource_cloudflare_teams_rules.go
  cloudflare/resource_cloudflare_teams_rules_test.go
  cloudflare/schema_cloudflare_teams_rules.go
  website/docs/r/teams_rule.html.markdown
Labels: workflow/pending-upstream-library
