Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2022-10, with the labels that each got.

#1948 update expression in documentation
  docs/resources/ruleset.md
  examples/resources/cloudflare_ruleset/resource.tf
Labels: workflow/skip-changelog-entry

#1805 Fetch/modify `origin_max_http_version` as a single setting
  .changelog/1805.txt
  internal/provider/resource_cloudflare_zone_settings_override.go
  internal/provider/resource_cloudflare_zone_settings_override_test.go
Labels: workflow/pending-maintainer-response

#1971 provider: make tf-log-check action idempotent
  .github/workflows/terraform-log-check.yml
  tools/cmd/tf-log-check/main.go
Labels: workflow/skip-changelog-entry

#1953 Issue 1840 Add custom_hostname wait_for_active_status
  .changelog/1953.txt
  docs/resources/custom_hostname.md
  docs/resources/device_posture_rule.md
  internal/provider/resource_cloudflare_custom_hostname.go
  internal/provider/resource_cloudflare_custom_hostname_test.go
  internal/provider/schema_cloudflare_custom_hostname.go
Labels: workflow/pending-cloudflare-response

#1957 add waiting room rules resource
  .changelog/1957.txt
  docs/resources/waiting_room_rules.md
  examples/resources/cloudflare_waiting_room_rules/import.sh
  examples/resources/cloudflare_waiting_room_rules/resource.tf
  internal/provider/provider.go
  internal/provider/resource_cloudflare_waiting_room_rules.go
  internal/provider/resource_cloudflare_waiting_room_rules_test.go
  internal/provider/schema_cloudflare_waiting_room_rules.go
Labels: workflow/pending-upstream-library

#1979 Create Total TLS Resource
  .changelog/1979.txt
  docs/resources/total_tls.md
  examples/resources/cloudflare_total_tls/resource.tf
  internal/provider/provider.go
  internal/provider/resource_cloudflare_total_tls.go
  internal/provider/resource_cloudflare_total_tls_test.go
  internal/provider/schema_cloudflare_total_tls.go
Labels: workflow/pending-upstream-library

#1706 Adds recently supported per_page/pagination teams_list
  .changelog/1706.txt
  internal/provider/resource_cloudflare_teams_list.go
  internal/provider/resource_cloudflare_teams_list_test.go
Labels: workflow/pending-upstream-library
