Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2023-08, with the labels that each got.

#2643 AUTH-5403 added access custom pages as a new resource
  .changelog/2643.txt
  docs/resources/access_application.md
  docs/resources/access_custom_page.md
  docs/resources/access_organization.md
  examples/resources/cloudflare_access_custom_page/resource.tf
  internal/sdkv2provider/provider.go
  internal/sdkv2provider/resource_cloudflare_access_application.go
  internal/sdkv2provider/resource_cloudflare_access_custom_page.go
  internal/sdkv2provider/resource_cloudflare_access_custom_page_test.go
  internal/sdkv2provider/resource_cloudflare_access_organization.go
  internal/sdkv2provider/schema_cloudflare_access_application.go
  internal/sdkv2provider/schema_cloudflare_access_custom_page.go
  internal/sdkv2provider/schema_cloudflare_access_organization.go
Labels: workflow/pending-upstream-library

#2664 Update cloudflare access group
  docs/resources/access_group.md
  examples/resources/cloudflare_access_group/resource.tf
Labels: workflow/skip-changelog-entry

#2602 Updates for `pages_project`
  .changelog/2602.txt
  docs/resources/pages_project.md
  internal/sdkv2provider/resource_cloudflare_pages_project_test.go
  internal/sdkv2provider/schema_cloudflare_notification_policy.go
  internal/sdkv2provider/schema_cloudflare_pages_project.go
Labels: lifecycle/stale

#2678 docs: use separate example IPs for customer and cloudflare endpoints
  docs/resources/gre_tunnel.md
  examples/resources/cloudflare_gre_tunnel/resource.tf
Labels: workflow/skip-changelog-entry

#2682 docs: update origin ca example
  docs/resources/origin_ca_certificate.md
  examples/resources/cloudflare_origin_ca_certificate/resource.tf
Labels: workflow/skip-changelog-entry
