Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2023-05, with the labels that each got.

#2279 Support `sentinelone` type in the `cloudflare_device_posture_rule` schema
  .changelog/2279.txt
  docs/resources/device_posture_rule.md
  internal/sdkv2provider/schema_cloudflare_device_posture_rule.go
Labels: workflow/pending-cloudflare-response

#2424 Add valid values to cloudflare_turnstile_widget.mode doc
  docs/resources/turnstile_widget.md
  internal/framework/service/turnstile/schema.go
Labels: workflow/skip-changelog-entry

#2427 centralise test skip logic across provider versions
  internal/sdkv2provider/provider_test.go
  internal/sdkv2provider/resource_cloudflare_account_member_test.go
  internal/sdkv2provider/resource_cloudflare_account_test.go
  internal/sdkv2provider/resource_cloudflare_authenticated_origin_pulls_certificate_test.go
  internal/sdkv2provider/resource_cloudflare_authenticated_origin_pulls_test.go
Labels: workflow/skip-changelog-entry

#2414 resource/cloudflare_ruleset: allow `FromValue.PreserveQueryString` to be nullable
  .changelog/2414.txt
  internal/framework/service/rulesets/resource.go
  internal/framework/service/rulesets/resource_test.go
Labels: workflow/pending-upstream-library

#2419 WR-1279 add waiting room zone-level settings
  .changelog/2419.txt
  docs/resources/waiting_room_settings.md
  examples/resources/cloudflare_waiting_room_settings/import.sh
  examples/resources/cloudflare_waiting_room_settings/resource.tf
  internal/sdkv2provider/provider.go
  internal/sdkv2provider/resource_cloudflare_waiting_room_settings.go
  internal/sdkv2provider/resource_cloudflare_waiting_room_settings_test.go
  internal/sdkv2provider/schema_cloudflare_waiting_room_settings.go
Labels: workflow/pending-upstream-library

#2455 resource/cloudflare_rulesets: update duplicateRulesets messaging to point to developer docs
  docs/resources/ruleset.md
  internal/framework/service/rulesets/resource.go
  templates/resources/ruleset.md.tmpl
Labels: workflow/skip-changelog-entry

#2456 add note about always updating to the latest version first to upgrade docs
  docs/guides/version-2-upgrade.md
  docs/guides/version-3-upgrade.md
  docs/guides/version-4-upgrade.md
  templates/guides/version-2-upgrade.md
  templates/guides/version-3-upgrade.md
  templates/guides/version-4-upgrade.md
Labels: workflow/skip-changelog-entry

#2459 resource/cloudflare_ruleset: add acctest coverage for validation edge_ttl/browser_ttl changes
  internal/framework/service/rulesets/resource_test.go
Labels: workflow/skip-changelog-entry

#2481 docs: add note to upgrade guide for cloudflare_rulesets
  docs/guides/version-4-upgrade.md
  templates/guides/version-4-upgrade.md
Labels: workflow/skip-changelog-entry
