Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2023-03, with the labels that each got.

#2269 Update doc for resource page_rule
  docs/resources/page_rule.md
  templates/resources/page_rule.md
Labels: workflow/skip-changelog-entry

#2288 automatically lock issues/PRs after a milestone release
  .github/workflows/milestone-closed.yml
Labels: workflow/skip-changelog-entry

#2297 resource/cloudflare_ruleset: mark `last_updated` and `description` as computed
  internal/framework/service/rulesets/resource_test.go
  internal/framework/service/rulesets/schema.go
Labels: workflow/skip-changelog-entry

#2309 tools/sync-github-issue-to-jira: introduce initial issue sync support
  .github/workflows/issue-sync.yml
  tools/cmd/sync-github-issue-to-jira/main.go
Labels: workflow/skip-changelog-entry

#2310 Update account member example
  docs/resources/access_organization.md
  docs/resources/account_member.md
  docs/resources/worker_script.md
  examples/resources/cloudflare_account_member/resource.tf
Labels: workflow/skip-changelog-entry

#2311 LB pool docs tidy up
  docs/resources/load_balancer_pool.md
  docs/resources/tunnel_config.md
  examples/resources/cloudflare_load_balancer_pool/import.sh
  internal/sdkv2provider/utils.go
Labels: workflow/skip-changelog-entry

#2330 Fix documentation link
  docs/index.md
  internal/framework/provider/provider.go
  internal/sdkv2provider/provider.go
Labels: workflow/skip-changelog-entry

#2313 AUTH-5081 Add claims and scopes fields to Access IDP config
  .changelog/2313.txt
  docs/resources/access_identity_provider.md
  internal/sdkv2provider/resource_cloudflare_access_identity_provider.go
  internal/sdkv2provider/schema_cloudflare_access_identity_provider.go
Labels: workflow/pending-upstream-library

#2303 feat: updated gateway rule action audit ssh and rule properties
  .changelog/2303.txt
  docs/resources/access_identity_provider.md
  docs/resources/teams_rule.md
  internal/sdkv2provider/resource_cloudflare_teams_rules.go
  internal/sdkv2provider/schema_cloudflare_teams_rules.go
Labels: workflow/pending-upstream-library

#2147 AUTH-4867 add scim_config to IDPs
  .changelog/2147.txt
  docs/resources/access_identity_provider.md
  internal/sdkv2provider/resource_cloudflare_access_identity_provider.go
  internal/sdkv2provider/resource_cloudflare_access_identity_provider_test.go
  internal/sdkv2provider/schema_cloudflare_access_identity_provider.go
Labels: workflow/pending-upstream-library, service/access
