Repository cloudflare/terraform-provider-cloudflare, pull requests merged in 2023-01, with the labels that each got.

#2130 fix device posture rule docs
  docs/resources/device_posture_rule.md
  internal/provider/resource_cloudflare_device_posture_rule_test.go
  internal/provider/schema_cloudflare_device_posture_rule.go
Labels: workflow/skip-changelog-entry

#2149 test/cloudflare_dlp_profile: make set assertions consistent
  internal/provider/resource_cloudflare_dlp_profile_test.go
Labels: workflow/skip-changelog-entry

#2151 Migrate data sources to autogen
  docs/data-sources/access_identity_provider.md
  docs/data-sources/account_roles.md
  docs/data-sources/devices.md
  docs/data-sources/ip_ranges.md
  docs/data-sources/origin_ca_root_certificate.md
  docs/data-sources/zone.md
  docs/data-sources/zone_dnssec.md
  docs/data-sources/zones.md
  examples/data-sources/cloudflare_access_identity_provider/data-source.tf
  examples/data-sources/cloudflare_account_roles/data-source.tf
  examples/data-sources/cloudflare_devices/data-source.tf
  examples/data-sources/cloudflare_ip_ranges/data-source.tf
  examples/data-sources/cloudflare_origin_ca_root_certificate/data-source.tf
  examples/data-sources/cloudflare_zone/data-source.tf
  examples/data-sources/cloudflare_zone_dnssec/data-source.tf
  examples/data-sources/cloudflare_zones/data-source.tf
  internal/provider/data_source_access_identity_provider.go
  internal/provider/data_source_account_roles.go
  internal/provider/data_source_devices.go
  internal/provider/data_source_ip_ranges.go
  internal/provider/data_source_origin_ca_root_certificate.go
  internal/provider/data_source_zone.go
  internal/provider/data_source_zone_dnssec.go
  internal/provider/data_source_zones.go
  internal/provider/schema_data_source_access_identity_provider.go
  internal/provider/schema_data_source_account_roles.go
  internal/provider/schema_data_source_cloudflare_devices.go
  templates/data-sources/access_identity_provider.md
  templates/data-sources/account_roles.md
  templates/data-sources/devices.md
  templates/data-sources/ip_ranges.md
  templates/data-sources/origin_ca_root_certificate.md
  templates/data-sources/zone.md
  templates/data-sources/zone.md.tmpl
  templates/data-sources/zone_dnssec.md
  templates/data-sources/zones.md
Labels: workflow/skip-changelog-entry

#2167 remove extra struct from UpdateDNSRecordParams
  internal/provider/resource_cloudflare_record.go
Labels: workflow/skip-changelog-entry

#2115 Add user_seat_expiration_inactive_time to Access organization
  .changelog/2115.txt
  docs/resources/access_organization.md
  examples/resources/cloudflare_access_organization/resource.tf
  internal/provider/resource_cloudflare_access_organization.go
  internal/provider/resource_cloudflare_access_organization_test.go
  internal/provider/schema_cloudflare_access_organization.go
Labels: service/access

#2073 feat: resource/cloudflare_access_group: supports ip_list property.
  .changelog/2073.txt
  docs/resources/access_group.md
  internal/provider/resource_cloudflare_access_group.go
  internal/provider/resource_cloudflare_access_group_test.go
  internal/provider/schema_cloudflare_access_group.go
Labels: workflow/pending-cloudflare-response, workflow/pending-public-documentation

#2186 provider: use `math.MaxInt32` for integer overflow checks
  internal/framework/provider/provider.go
  internal/sdkv2provider/provider.go
Labels: workflow/skip-changelog-entry
